### ISSUE TITLE
[bug] Module not found due to inconsistent naming

### ISSUE THREAD

**Issue by JChris246** [BoopChat/boop#33]
## Verbose log

npm WARN lifecycle The node binary used for scripts is /snap/bin/node but npm is using /snap/node/5320/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> server@0.0.0 dev /home/pi/docker_images/boop/server
> nodemon ./bin/www

[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node ./bin/www`
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '../controllers/contacts'
Require stack:
- /home/pi/docker_images/boop/server/routes/contacts.js
- /home/pi/docker_images/boop/server/app.js
- /home/pi/docker_images/boop/server/bin/www
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/pi/docker_images/boop/server/routes/contacts.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/docker_images/boop/server/routes/contacts.js',
    '/home/pi/docker_images/boop/server/app.js',
    '/home/pi/docker_images/boop/server/bin/www'
  ]
}
[nodemon] app crashed - waiting for file changes before starting...

## Description

The above error log occurs when trying to run `npm run dev`. This is due to the route files Contacts.js, Conversations.js, Messages.js, Participants.js, SigninOptions.js and Users.js requiring/importing their respective controller modules spelling them in all lower case letters (e.g. `var controller = require("../controllers/contacts");`). The names of the actual controller files are in Upper Camel Case (`/boop/server/controllers/Contacts.js`) and a result, the require statement fails to load the module on unix-like systems.

## Suggested fix

This bug can be rectified by renaming either the controller files or adjusting import statements to match the file names.

**Comment by krazeelazy** [comment]
I'll adjust the imports
